### ISSUE TITLE
THREE.Raycaster: Unsupported camera type.

### ISSUE THREAD

**Issue by quantumalchemy** [mwbeene/aframe-cursor-teleport#1]
When adding a cursor or any other entity inside the camera ie : cursors, hud .. etc getting conflicts
 error: THREE.Raycaster: Unsupported camera type.
and aframe-cursor-teleport is disabled.

EXAMPLE:
```
  <a-entity id="cameraRig" cursor-teleport="cameraRig: #cameraRig; cameraHead: #head; collisionEntities: .collision; ignoreEntities: .clickable">
        <a-entity id="head" position="0 1.52 0" camera look-controls="reverseMouseDrag: true">
        <a-cursor id="lookpointer" fuse="true" color="red"></a-cursor>
        <a-entity id="HUD" geometry="primitive: plane; height: 0.2; width: 0.2" position="0 0 -1"
            material="color: gray; opacity: 0.5"></a-entity>
        </a-entity>
    </a-entity>
```

**Comment by mwbeene** [comment]
Thanks for pointing this out. I updated the component so that it traverses the cameraHead entity to find the camera rather than selecting the first child like it was before. Now it should work with child entities like your HUD.

Let me know if this works!

**Comment by quantumalchemy** [comment]
Wow! That was fast
Works great ! Thanks !
This is the best loco / teleport comp. for a-frame
